### PR TITLE
remove workaround to install z-push now that the packaging is fixed

### PR DESCRIPTION
**Pull request by jacalvo**
this should fix the issue once the new z-push package with the fix in the postinst is published

### CODE REVIEW

**Comment by exekias** [comment]
barbaric, does this auto accept the license?

check syntax lint so we can merge

**Comment by jacalvo** [comment]
I think we should wait for @papajulio  confirmation of the new z-push is released before merging, otherwise there will be regression now that the workaround has been removed with my last commits

**Comment by sixstone-qq** [comment]
@jacalvo it would be great if you squash the 4 commits to one :)

**Comment by jacalvo** [comment]
That can be done easier with merge --squash at the moment of the merge, better than rebasing already pushed stuff I think...

**Comment by exekias** [comment]
I would prefer to merge things that have been discussed before, so merge --squash is not very friendly, you can always push --force here or, if you don't like it, push the squash to another branch

**Comment by jacalvo** [comment]
deprecated by https://github.com/Zentyal/zinc/pull/15

**Pull request closed without merging**
